
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[285] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  120,  106,
      102,  103,   56,  101,   92,  106,   68,   70,   46,   47,
       66,   64,   53,   65,   45,   67,   99,   99,   93,   52,
       62,   57,   60,  106,   94,   50,   51,   72,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   48,   71,   49,   73,  111,
      110,  111,  108,  107,  118,  113,  112,  117,   59,   96,
       78,   54,   79,   69,   76,   99,   99,   74,   75,  105,
      104,   77,  100,    0,   99,   91,   83,   63,   58,   90,
       61,   82,    0,   97,   94,   81,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   14,   95,   18,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   80,   55,  109,  114,  116,  115,   96,  100,   85,
       87,   86,   84,   98,   97,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   17,    1,   11,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   37,   95,
       95,   95,   95,   95,   95,   95,   12,   95,   95,   95,
       95,   95,   95,   89,   88,   98,   95,   95,   95,   21,
       95,   95,   95,   15,   95,   95,   95,   95,   41,   95,

       13,   95,   95,   95,   95,   95,   95,   95,   95,   40,
       95,   95,   95,   28,   95,   95,   95,   95,   35,   20,
       29,   38,   27,   24,    2,   42,   95,   95,   95,   95,
       36,   95,   34,   95,   95,   95,   95,   95,   95,   31,
       95,   95,   39,   95,   32,   95,   23,   95,   95,   95,
       16,   95,   95,   43,   33,   95,   95,   95,    7,    3,
       95,   95,   26,   44,   19,   95,   95,   95,    5,   95,
       95,   95,   95,   95,   30,   25,   10,   95,    6,   22,
        8,    9,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   31,   48,   49,   50,   51,   52,   53,   54,
       55,   31,   56,   57,   58,   59,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[60] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    1,
        1,    1,    1,    1,    3,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[296] =
    {   0,
        0,    0,   57,   58,  322,  321,   59,   60,  323,  326,
      326,  326,  299,  326,  326,    0,  298,   57,  326,  326,
       55,   53,  326,   56,  326,   69,   66,   75,  300,  326,
       67,   72,   74,  294,    0,  326,  326,  295,    0,  274,
       25,   67,   57,   69,   76,   89,  270,  269,  274,  265,
      276,  275,   78,  262,   63,  326,   60,  326,  326,  326,
      326,  292,  326,  326,  326,  326,  326,   99,  326,    0,
      326,  326,  326,  326,  326,   89,  114,  326,  326,  326,
      326,  326,  117,  122,  127,  326,  125,  326,  326,  326,
      326,  127,    0,    0,    0,  326,    0,  268,  261,  270,

      256,  272,  258,  253,  265,  250,  256,  250,  252,  246,
      249,  244,  247,  256,    0,  246,   66,  254,  249,  253,
      244,  251,  237,  117,  111,  252,  236,  242,  230,  244,
      229,  326,  326,  326,  326,  326,  326,    0,  137,  255,
      326,  326,  254,    0,    0,  244,  241,  242,  223,  223,
      108,  235,  222,  233,  219,    0,    0,    0,  234,  220,
      233,  214,  217,  226,  215,  212,  214,  207,    0,  221,
      207,  209,  222,  114,  216,  200,    0,  201,  214,  199,
      212,  202,  207,  326,  326,    0,  196,  202,  201,    0,
      193,  191,  200,  199,  183,  192,  200,  203,    0,  189,

        0,  185,  184,  188,  198,  179,  185,  179,  180,    0,
      175,  169,  175,    0,  186,  181,  172,  185,    0,    0,
      172,    0,    0,    0,    0,    0,  172,  179,  169,  179,
        0,  170,    0,  176,  174,  158,  159,  159,  171,    0,
      161,  165,    0,  159,    0,  169,    0,  163,  150,  149,
        0,  154,  149,    0,    0,  165,  159,  146,    0,    0,
      157,  134,    0,    0,    0,  133,  130,  128,    0,  129,
      104,   94,   94,   87,    0,    0,    0,   85,    0,    0,
        0,    0,    0,  326,  167,  171,  175,  102,  177,  180,
      183,  186,   73,  189,  192

    } ;

static yyconst flex_int16_t yy_def[296] =
    {   0,
      284,    1,  285,  285,  286,  286,  287,  287,  284,  284,
      284,  284,  284,  284,  284,  288,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  289,  290,  284,  284,  284,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  292,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  293,  294,  290,  284,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  284,  284,  284,  284,  284,  284,  292,  284,  284,
      284,  284,  284,  295,  294,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  284,  284,  295,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284

    } ;

static yyconst flex_int16_t yy_nxt[386] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   10,   37,   38,
       39,   40,   41,   42,   39,   43,   44,   45,   39,   46,
       47,   39,   39,   48,   49,   50,   51,   52,   53,   54,
       39,   39,   55,   39,   39,   56,   57,   58,   59,   61,
       61,   66,   66,   67,   67,   72,   74,   99,   62,   62,
       76,   77,  100,   76,   77,   78,  144,   75,   79,   73,
       80,   83,  132,   84,   84,   81,   68,   68,   87,   88,
       83,   82,   85,   85,   89,   90,   91,   92,  101,  104,

      107,  130,  131,  135,   83,   70,   84,   84,  105,  102,
      106,  110,  103,  125,  108,  164,  133,  165,  111,  109,
      283,  112,  282,  113,  114,  115,  116,  126,  127,   83,
      128,   85,   85,  117,  139,  139,  281,   83,  118,   84,
       84,  280,   83,  136,   85,   85,  140,  141,  137,  142,
      143,  172,  279,  175,  139,  139,  192,  193,  176,  173,
      177,  212,  278,  277,  213,  276,  174,   60,   60,   60,
       60,   63,   63,   63,   63,   65,   65,   65,   65,   94,
       94,   95,  275,   95,   97,  274,   97,  138,  273,  138,
      145,  272,  145,  186,  271,  186,  270,  269,  268,  267,

      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  191,  190,  189,  188,  187,  185,  184,  183,  182,
      181,  180,  179,  178,  171,  170,  169,  168,  167,  166,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,

      153,  152,  151,  150,  149,  148,  147,  146,  134,  129,
      124,  123,  122,  121,  120,  119,   98,   96,   93,   86,
       71,   69,  284,   64,   64,    9,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284
    } ;

static yyconst flex_int16_t yy_chk[386] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,    8,    7,    8,   18,   21,   41,    3,    4,
       22,   22,   41,   24,   24,   22,  293,   21,   24,   18,
       26,   27,   57,   27,   27,   26,    7,    8,   31,   31,
       28,   26,   28,   28,   32,   32,   33,   33,   42,   43,

       44,   55,   55,   68,   76,  288,   76,   76,   43,   42,
       43,   45,   42,   53,   44,  117,   57,  117,   45,   44,
      278,   45,  274,   45,   45,   46,   46,   53,   53,   77,
       53,   77,   77,   46,   83,   83,  273,   84,   46,   84,
       84,  272,   85,   68,   85,   85,   87,   87,   68,   92,
       92,  124,  271,  125,  139,  139,  151,  151,  125,  124,
      125,  174,  270,  268,  174,  267,  124,  285,  285,  285,
      285,  286,  286,  286,  286,  287,  287,  287,  287,  289,
      289,  290,  266,  290,  291,  262,  291,  292,  261,  292,
      294,  258,  294,  295,  257,  295,  256,  253,  252,  250,

      249,  248,  246,  244,  242,  241,  239,  238,  237,  236,
      235,  234,  232,  230,  229,  228,  227,  221,  218,  217,
      216,  215,  213,  212,  211,  209,  208,  207,  206,  205,
      204,  203,  202,  200,  198,  197,  196,  195,  194,  193,
      192,  191,  189,  188,  187,  183,  182,  181,  180,  179,
      178,  176,  175,  173,  172,  171,  170,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  155,  154,  153,
      152,  150,  149,  148,  147,  146,  143,  140,  131,  130,
      129,  128,  127,  126,  123,  122,  121,  120,  119,  118,
      116,  114,  113,  112,  111,  110,  109,  108,  107,  106,

      105,  104,  103,  102,  101,  100,   99,   98,   62,   54,
       52,   51,   50,   49,   48,   47,   40,   38,   34,   29,
       17,   13,    9,    6,    5,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "iris.l"
#line 2 "iris.l"
#include "Iris.h"
#include "y.tab.h"

extern char* g_pCurrentString;
extern int g_nCurrentStringLength;
extern int g_nReadLength;

extern "C" int yywrap(void) {
    return 1;
}

extern "C" int StringRead(char* pBuffer, int nMaxToRead) {
	int nLengthToRead = g_nCurrentStringLength - g_nReadLength > nMaxToRead ? nMaxToRead : g_nCurrentStringLength - g_nReadLength;
	
	for(int i = 0; i < nLengthToRead; ++i) {
		pBuffer[i] = g_pCurrentString[g_nReadLength + i];
	}
	
	g_nReadLength += nLengthToRead;
	return nLengthToRead;
}

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) result = StringRead(buf, max_size);


#line 658 "lex.yy.c"

#define INITIAL 0
#define MULTIPLE_LINE_COMMENT_STATE 1
#define SINGLE_LINE_COMMENT_STATE 2
#define STRING_LITERAL_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 29 "iris.l"

#line 845 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 326 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "iris.l"
return FUNCTION;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "iris.l"
return CLASS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "iris.l"
return MODULE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "iris.l"
return INTERFACE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "iris.l"
return EXTENDS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "iris.l"
return INVOLVES;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "iris.l"
return JOINTS;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "iris.l"
return PERSONAL;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "iris.l"
return RELATIVE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "iris.l"
return EVERYONE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "iris.l"
return GET;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "iris.l"
return SET;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "iris.l"
return GSET;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "iris.l"
return IF;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 44 "iris.l"
return ELSE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "iris.l"
return ELSEIF;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 46 "iris.l"
return FOR;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 47 "iris.l"
return IN;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 48 "iris.l"
return SWITCH;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 49 "iris.l"
return WHEN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "iris.l"
return CAST;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "iris.l"
return ITERATOR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "iris.l"
return SUPER;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "iris.l"
return BREAK;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "iris.l"
return CONTINUE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "iris.l"
return RETURN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "iris.l"
return BLOCK;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "iris.l"
return SELF;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "iris.l"
return WITH;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "iris.l"
return WITHOUT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 60 "iris.l"
return ORDER;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 61 "iris.l"
return SERVE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 62 "iris.l"
return IGNORE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 63 "iris.l"
return GROAN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 64 "iris.l"
return TRUE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 65 "iris.l"
return FALSE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "iris.l"
return NIL;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 68 "iris.l"
return ALIAS;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "iris.l"
return RETRY;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 70 "iris.l"
return REDO;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "iris.l"
return GOTO;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 72 "iris.l"
return CONST;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "iris.l"
return GLOBAL;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 74 "iris.l"
return STATIC;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "iris.l"
return DOT;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 77 "iris.l"
return LP;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 78 "iris.l"
return RP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "iris.l"
return LC;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "iris.l"
return RC;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "iris.l"
return LB;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "iris.l"
return RB;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "iris.l"
return SEMICOLON;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "iris.l"
return COMMA;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "iris.l"
return LOGICAL_AND;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "iris.l"
return LOGICAL_OR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "iris.l"
return LOGICAL_NOT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "iris.l"
return ASSIGN;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "iris.l"
return EQ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "iris.l"
return NE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "iris.l"
return GT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "iris.l"
return GE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "iris.l"
return LT;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "iris.l"
return LE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "iris.l"
return ADD;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "iris.l"
return SUB;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "iris.l"
return MUL;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "iris.l"
return DIV;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "iris.l"
return MOD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "iris.l"
return POWER;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "iris.l"
return BIT_AND;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "iris.l"
return BIT_OR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "iris.l"
return BIT_XOR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "iris.l"
return BIT_NOT;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "iris.l"
return ASSIGN_ADD;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "iris.l"
return ASSIGN_SUB;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "iris.l"
return ASSIGN_MUL;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "iris.l"
return ASSIGN_DIV;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "iris.l"
return ASSIGN_MOD;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "iris.l"
return ASSIGN_BIT_AND;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "iris.l"
return ASSIGN_BIT_OR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "iris.l"
return ASSIGN_BIT_XOR;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "iris.l"
return BIT_SHR;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "iris.l"
return BIT_SHL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "iris.l"
return BIT_SAR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "iris.l"
return BIT_SAL;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "iris.l"
return ASSIGN_BIT_SHR;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "iris.l"
return ASSIGN_BIT_SHL;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "iris.l"
return ASSIGN_BIT_SAR;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "iris.l"
return ASSIGN_BIT_SAL;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "iris.l"
return ITER;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "iris.l"
return FILED;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "iris.l"
return SHARP;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "iris.l"
return CONLON;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 126 "iris.l"
{
	//标识符-常量
	yylval.m_pIdentifier = new IrisIdentifier(IrisIdentifier::IdentifilerType::Constance, yytext);
	return IDENTIFIER;	
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 131 "iris.l"
{
	// 标识符-局部变量
	yylval.m_pIdentifier = new IrisIdentifier(IrisIdentifier::IdentifilerType::LocalVariable, yytext);
	return IDENTIFIER;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 136 "iris.l"
{
	// 标识符-全局变量
	yylval.m_pIdentifier = new IrisIdentifier(IrisIdentifier::IdentifilerType::GlobalVariable, yytext);
	return IDENTIFIER;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 141 "iris.l"
{
	// 标识符-实例变量
	yylval.m_pIdentifier = new IrisIdentifier(IrisIdentifier::IdentifilerType::InstanceVariable, yytext);
	return IDENTIFIER;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 146 "iris.l"
{
	// 标识符-类变量
	yylval.m_pIdentifier = new IrisIdentifier(IrisIdentifier::IdentifilerType::ClassVariable, yytext);
	return IDENTIFIER;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "iris.l"
{
	//整数
	IrisExpression* pExpression = IrisExpression::CreateNativeObjectExpression(IrisExpression::ExpressionType::Integer,
			IrisInterpreter::CurInstance()->GetIrisClass("Integer")->CreateInstanceFromLiteral(yytext).GetObject());
	yylval.m_pExpression = pExpression;
	return INTEGER;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 160 "iris.l"
{
	//浮点数
	IrisExpression* pExpression = IrisExpression::CreateNativeObjectExpression(IrisExpression::ExpressionType::Float,
			IrisInterpreter::CurInstance()->GetIrisClass("Float")->CreateInstanceFromLiteral(yytext).GetObject());
	yylval.m_pExpression = pExpression;
	return FLOAT;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 168 "iris.l"
{
	//开始字符串
	IrisInterpreter::CurInstance()->StartStringProcess();
	BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 174 "iris.l"
{;}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 175 "iris.l"
{
	IrisInterpreter::CurInstance()->IncreamLineNumber();
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 178 "iris.l"
{
	// 开始单行注释
	BEGIN SINGLE_LINE_COMMENT_STATE;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 182 "iris.l"
{
	// 开始多行注释
	BEGIN MULTIPLE_LINE_COMMENT_STATE;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 187 "iris.l"
{
	// 错误处理
	//IrisInterpreter::CurInstance()->GroanIrregular(IrisInterpreter::CurInstance()->GetCurrentLineNumber(), new IrisSyntaxIrregular());
	//fprintf(stderr, "Grammar Error !\n");
	//exit(0);
	IrisInterpreter::CurInstance()->GroanFatalIrregular(IrisInterpreter::FatalIrregular::SyntaxIrregular, IrisInterpreter::CurInstance()->GetCurrentLineNumber(), "");
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 195 "iris.l"
{
	return EOF;
}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 199 "iris.l"
{
	// 结束单行注释
	IrisInterpreter::CurInstance()->IncreamLineNumber();
	BEGIN INITIAL;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 204 "iris.l"
;
	YY_BREAK
case YY_STATE_EOF(SINGLE_LINE_COMMENT_STATE):
#line 206 "iris.l"
{
	return EOF;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 210 "iris.l"
{
	// 结束多行注释
	BEGIN INITIAL;
}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 214 "iris.l"
{
	IrisInterpreter::CurInstance()->IncreamLineNumber();
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 217 "iris.l"
;
	YY_BREAK
case YY_STATE_EOF(MULTIPLE_LINE_COMMENT_STATE):
#line 219 "iris.l"
{
	return EOF;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 223 "iris.l"
{
	// 终止字符串
	IrisExpression* pExpression = IrisExpression::CreateNativeObjectExpression(IrisExpression::ExpressionType::String,
		IrisInterpreter::CurInstance()->GetIrisClass("String")->CreateInstanceByInstantValue(IrisInterpreter::CurInstance()->EndStringProcess()).GetObject());
	yylval.m_pExpression = pExpression;
	BEGIN INITIAL;
	return STRING;
}
	YY_BREAK
case 113:
/* rule 113 can match eol */
YY_RULE_SETUP
#line 231 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar('\n');
	IrisInterpreter::CurInstance()->IncreamLineNumber();
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 235 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar('"');
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 238 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar('\t');
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 241 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar('\n');
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 244 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar('\\');
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 247 "iris.l"
{
	IrisInterpreter::CurInstance()->AddStringChar(yytext[0]);
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 250 "iris.l"
ECHO;
	YY_BREAK
#line 1624 "lex.yy.c"
case YY_STATE_EOF(STRING_LITERAL_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "iris.l"


