#ifndef  _H_IRIS2DCOMPILERCONFIGURE_
#define  _H_IRIS2DCOMPILERCONFIGURE_

#define IR_USE_DEPRECATED_API 0
#define IR_EXPORT_C_API 0

#define IR_DOC_LANG_ENUS 0
#define IR_DOC_LANG_ZHCN 1

#define IR_DOC_LANG IR_DOC_LANG_ZHCN

#define ENGLISH IR_DOC_LANG == IR_DOC_LANG_ENUS
#define CHINESE IR_DOC_LANG == IR_DOC_LANG_ZHCN

#endif // ! _H_IRIS2DCOMPILERCONFIGURE_

