var menudata={children:[
{text:"首页",url:"index.html"},
{text:"命名空间",url:"namespaces.html",children:[
{text:"命名空间列表",url:"namespaces.html"}]},
{text:"类",url:"annotated.html",children:[
{text:"类列表",url:"annotated.html"},
{text:"类索引",url:"classes.html"},
{text:"类成员",url:"functions.html",children:[
{text:"全部",url:"functions.html",children:[
{text:"c",url:"functions.html#index_c"},
{text:"g",url:"functions.html#index_g"},
{text:"i",url:"functions.html#index_i"},
{text:"m",url:"functions.html#index_m"},
{text:"n",url:"functions.html#index_n"},
{text:"q",url:"functions.html#index_q"},
{text:"r",url:"functions.html#index_r"},
{text:"s",url:"functions.html#index_s"},
{text:"u",url:"functions.html#index_u"}]},
{text:"函数",url:"functions_func.html",children:[
{text:"c",url:"functions_func.html#index_c"},
{text:"g",url:"functions_func.html#index_g"},
{text:"i",url:"functions_func.html#index_i"},
{text:"q",url:"functions_func.html#index_q"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"},
{text:"u",url:"functions_func.html#index_u"}]},
{text:"变量",url:"functions_vars.html"},
{text:"类型定义",url:"functions_type.html"}]}]},
{text:"文件",url:"files.html",children:[
{text:"文件列表",url:"files.html"}]}]}
