#ifndef  _H_COMPILER_CONFIGURE_
#define  _H_COMPILER_CONFIGURE_

#define IR_COMPILE_USE_RESULT_REPORT 1
#define IR_USE_PROPERTY_DIRTY_CHECK 1

#define IR_VERTEX_BUFFER_NUM 2
#define IR_VERTEX_BUFFER_MAX_SIZE 128
#define IR_MAX_BATCH_SPRITE_SIZE IR_VERTEX_BUFFER_MAX_SIZE

#endif // ! _H_COMPILER_CONFIGURE_
